config/routes.rb
Hajis::Application.routes.draw do
  resources :farms

  resources :customers

  resources :home

  devise_for :users

  resources :credit_debit
  match 'accounts' => 'account#index'
  match '/accounts/manage' => 'account#manage'
  post '/customer_amount/calculate' => 'account#calculate'
  put '/customer_account/edit/:id' => 'account#edit'
  put '/customer_account/update/:id' => 'account#update'
  match '/daily_report' => 'account#daily_report'
  

  root :to => 'account#index'

end

app/models/farm.rb
class Farm < ActiveRecord::Base
  attr_accessible :country, :latitude, :longitude, :name, :phone, :place, :state, :street, :distance

  validates_presence_of :street, :state, :name, :place
  validates :phone,:presence => true,
            :numericality => true,
            :length => { :minimum => 10, :maximum => 15 }

  after_validation :geocode, if: lambda { |l| l.address.present? }
  geocoded_by :address

  before_save :assign_distance

  default_scope { where("phone != #{HOME_PHONE}") }

  # Getter method for concat address components.
  def address
    [street, place, state, country].join(', ')
  end

  def distance_to_display
    distance.round(2)
  end

  def display_name
    "#{name}(#{place})"
  end

  private
    def assign_distance
      home_farm = self.class.unscoped.where(phone: HOME_PHONE).first
      return if home_farm.nil?

      self.distance = home_farm.distance_to([self.latitude, self.longitude])
    end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  # GET /farms
  # GET /farms.json
  def index
    @farms = Farm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @farms }
    end
  end

  # GET /farms/1
  # GET /farms/1.json
  def show
    @farm = Farm.find(params[:id])
    @hash = Gmaps4rails.build_markers(@farm) do |farm, marker|
      marker.lat farm.latitude
      marker.lng farm.longitude
      marker.infowindow farm.address
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @farm }
    end
  end

  # GET /farms/new
  # GET /farms/new.json
  def new
    @farm = Farm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @farm }
    end
  end

  # GET /farms/1/edit
  def edit
    @farm = Farm.find(params[:id])
  end

  # POST /farms
  # POST /farms.json
  def create
    @farm = Farm.new(params[:farm])

    respond_to do |format|
      if @farm.save
        format.html { redirect_to @farm, notice: 'Farm was successfully created.' }
        format.json { render json: @farm, status: :created, location: @farm }
      else
        format.html { render action: "new" }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /farms/1
  # PUT /farms/1.json
  def update
    @farm = Farm.find(params[:id])

    respond_to do |format|
      if @farm.update_attributes(params[:farm])
        format.html { redirect_to @farm, notice: 'Farm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farms/1
  # DELETE /farms/1.json
  def destroy
    @farm = Farm.find(params[:id])
    @farm.destroy

    respond_to do |format|
      format.html { redirect_to farms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/views/farms/_form.html.erb
<div class='panel-body'>
  <%= form_for(@farm, html: { class: 'form-horizontal' }) do |f| %>
    <% if @farm.errors.any? %>
      <div id="error_explanation" class='alert alert-danger' role='alert'>
        <h2><%= pluralize(@farm.errors.count, "error") %> prohibited this farm from being saved:</h2>

        <ul>
        <% @farm.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class='form-group'>
      <label class="col-sm-2 control-label"><%= f.label :name %></label>
      <div class="col-xs-4">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name'  %>
      </div>
    </div>
    <div class='form-group'>
      <label class="col-sm-2 control-label"><%= f.label :street %></label>
      <div class="col-xs-4">
        <%= f.text_field :street, class: 'form-control', placeholder: 'Street' %>
      </div>
    </div>
    <div class='form-group'>
      <label class="col-sm-2 control-label"><%= f.label :place %></label>
      <div class="col-xs-4">
        <%= f.text_field :place, class: 'form-control', placeholder: 'Place' %>
      </div>
    </div>
    <div class='form-group'>
      <label class="col-sm-2 control-label"><%= f.label :state %></label>
      <div class="col-xs-4">
        <%= f.text_field :state, class: 'form-control', placeholder: 'State' %>
      </div>
    </div>
    <div class='form-group'>
      <label class="col-sm-2 control-label"><%= f.label :phone %></label>
      <div class="col-xs-4">
        <%= f.text_field :phone, class: 'form-control', placeholder: 'Phone' %>
      </div>
    </div>
    <div class="actions">
      <%= f.submit 'Save', class: 'btn btn-default' %>
    </div>
  <% end %>
</div>

app/views/farms/edit.html.erb
<div class="col-md-12">
  <div class='panel panel-info'>
    <div class="panel-heading">Edit farm</div>
  </div>
  <%= render 'form' %>
</div>

<%= link_to 'Show', @farm %> |
<%= link_to 'Back', farms_path %>

app/views/farms/index.html.erb
<h3>Farms</h3>

<table class='table table-striped'>
  <tr>
    <th>Name</th>
    <th>Street</th>
    <th>Place</th>
    <th>State</th>
    <th>Country</th>
    <th>Phone</th>
    <th></th>
    <th>Actions</th>
    <th></th>
  </tr>

<% @farms.each do |farm| %>
  <tr>
    <td><%= farm.name %></td>
    <td><%= farm.street %></td>
    <td><%= farm.place %></td>
    <td><%= farm.state %></td>
    <td><%= farm.country %></td>
    <td><%= farm.phone %></td>
    <td><%= link_to 'Show', farm %></td>
    <td><%= link_to 'Edit', edit_farm_path(farm) %></td>
    <td><%= link_to 'Destroy', farm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Farm', new_farm_path %>

app/views/farms/new.html.erb
<div class="col-md-12">
  <div class='panel panel-info'>
    <div class="panel-heading">Add farm</div>
  </div>
  <%= render 'form' %>
</div>

<%= link_to 'Back', farms_path %>

app/views/farms/show.html.erb
<div class='col-md-12'>
  <div class='col-md-6'>
    <p id="notice"><%= notice %></p>
  <p>
    <b>Name:</b>
    <%= @farm.name %>
  </p>

  <p>
    <b>Street:</b>
    <%= @farm.street %>
  </p>

  <p>
    <b>Place:</b>
    <%= @farm.place %>
  </p>

  <p>
    <b>State:</b>
    <%= @farm.state %>
  </p>

  <p>
    <b>Country:</b>
    <%= @farm.country %>
  </p>

  <p>
    <b>Phone:</b>
    <%= @farm.phone %>
  </p>
  </div>
  <div class='col-md-6'>
    <div>
      <div id="map" style='width: 100%; height: 400px;'></div>
    </div>
  </div>
  <%= link_to 'Edit', edit_farm_path(@farm) %> |
  <%= link_to 'Back', farms_path %>
</div>
<%= render 'common/map_widget' %>