config/routes.rb
Hajis::Application.routes.draw do
  resources :farms

  resources :customers

  resources :home

  devise_for :users

  resources :credit_debit
  match 'accounts' => 'account#index'
  match '/accounts/manage' => 'account#manage'
  post '/customer_amount/calculate' => 'account#calculate'
  put '/customer_account/edit/:id' => 'account#edit'
  put '/customer_account/update/:id' => 'account#update'
  match '/daily_report' => 'account#daily_report'
  

  root :to => 'account#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :get_rails_data, only: [:index]

	def index
		@customers = Customer.order('old_balance DESC')
	end

	private

		def get_rails_data
			@rails_sales_data = CustomerAccount.group_by_date.map {
														|k, v|
															{
																date: k,
																amount: v.map(&:amount).sum,
																balance: v.map(&:balance_amount).sum,
																weight_loss: (v.map(&:shed_kg).sum - v.map(&:vehicle_kg).sum)
															}
													}
			@rails_farm_data = Farm.all.map { |m| { label: m.display_name, value: m.distance_to_display } }
		end
end

app/views/home/shared/_donut_chart.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Farm Distance (km)
  </div>
  <div class="panel-body">
    <div id="morris-donut-chart"></div>
  </div>
</div>

<script type="text/javascript">
	var javascript_data = <%= raw @rails_farm_data.to_json %>;
  Morris.Donut({
        element: 'morris-donut-chart',
        data: javascript_data,
        resize: true
    });
</script>

app/views/home/shared/_notification_panel.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Notifications Panel
  </div>
  <!-- /.panel-heading -->
  <div class="panel-body">
    <div class="list-group">
      <a href="#" class="list-group-item">
      <i class="fa fa-comment fa-fw"></i> New Comment
      <span class="pull-right text-muted small"><em>4 minutes ago</em>
      </span>
      </a>
      <a href="#" class="list-group-item">
      <i class="fa fa-twitter fa-fw"></i> 3 New Followers
      <span class="pull-right text-muted small"><em>12 minutes ago</em>
      </span>
      </a>
      <a href="#" class="list-group-item">
      <i class="fa fa-envelope fa-fw"></i> Message Sent
      <span class="pull-right text-muted small"><em>27 minutes ago</em>
      </span>
      </a>
      <a href="#" class="list-group-item">
      <i class="fa fa-tasks fa-fw"></i> New Task
      <span class="pull-right text-muted small"><em>43 minutes ago</em>
      </span>
      </a>
      <a href="#" class="list-group-item">
      <i class="fa fa-upload fa-fw"></i> Server Rebooted
      <span class="pull-right text-muted small"><em>11:32 AM</em>
      </span>
      </a>
      <a href="#" class="list-group-item">
      <i class="fa fa-bolt fa-fw"></i> Server Crashed!
      <span class="pull-right text-muted small"><em>11:13 AM</em>
      </span>
      </a>
      <a href="#" class="list-group-item">
      <i class="fa fa-warning fa-fw"></i> Server Not Responding
      <span class="pull-right text-muted small"><em>10:57 AM</em>
      </span>
      </a>
      <a href="#" class="list-group-item">
      <i class="fa fa-shopping-cart fa-fw"></i> New Order Placed
      <span class="pull-right text-muted small"><em>9:49 AM</em>
      </span>
      </a>
      <a href="#" class="list-group-item">
      <i class="fa fa-money fa-fw"></i> Payment Received
      <span class="pull-right text-muted small"><em>Yesterday</em>
      </span>
      </a>
    </div>
    <!-- /.list-group -->
    <a href="#" class="btn btn-default btn-block">View All Alerts</a>
  </div>
  <!-- /.panel-body -->
</div>
<!-- /.panel -->

app/views/home/shared/_old_balance_wrapper.html.erb
<% @customers.each do |customer| %>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-red">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            Old Balance
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge" style='font-size: 25px;'><%= to_currency(customer.old_balance) %></div>
          </div>
        </div>
      </div>
      <a href="<%= customer_path(customer.id) %>">
        <div class="panel-footer">
          <span class="pull-left"><%= customer.name %></span>
        <div class="clearfix"></div>
      </div>
      </a>
    </div>
  </div>
<% end %>

app/views/home/shared/_sales_chart.html.erb
<div class="col-lg-8">
  <div class="panel panel-default">
    <div class="panel-heading">
      Daily Sales
    </div>
    <div class="panel-body">
      <div id="morris-area-chart"></div>
    </div>
  </div>
</div>

<script type="text/javascript">
  var script_data = <%= raw @rails_sales_data.to_json %>;
  new Morris.Area({
      element: 'morris-area-chart',
      data: script_data,
      xkey: 'date',
      ykeys: ['amount', 'balance', 'weight_loss'],
      labels: ['Closing Amount', 'Balance Amount', 'Weight Loss'],
      pointSize: 2,
      hideHover: 'auto',
      resize: true
  });
</script>