config/routes.rb
Hajis::Application.routes.draw do
  resources :farms

  resources :customers

  resources :home

  devise_for :users

  resources :credit_debit
  match 'accounts' => 'account#index'
  match '/accounts/manage' => 'account#manage'
  post '/customer_amount/calculate' => 'account#calculate'
  put '/customer_account/edit/:id' => 'account#edit'
  put '/customer_account/update/:id' => 'account#update'
  match '/daily_report' => 'account#daily_report'
  

  root :to => 'account#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hajis</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "/js/methods.js" %>

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
	<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
	<%= render template: "layouts/header" %>
<% end %>
<br />
<div class="container">
	<%= yield %>
</div>
<%= render template: 'layouts/footer' %>
</body>
</html>

app/views/layouts/footer.html.erb
<div class="footer">
	<p>© Hajis <%= Time.now.year %></p>
</div>

app/views/layouts/header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Haji's Farms</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <%= content_tag :li, class: ('active' if controller_name == 'home') do %>
              <a href="<%= home_index_path %>">Home</a>
            <% end %>
            <%= content_tag :li, class: ('active' if controller_name == 'customers') do %>
              <a href="<%= customers_path %>">Shops</a>
            <% end %>
            <%= content_tag :li, class: ('active' if controller_name == 'farms') do %>
              <a href="<%= farms_path %>">Farms</a>
            <% end %>
            <%= content_tag :li, class: ('active' if controller_name == 'employees') do %>
              <a href="#">Employees</a>
            <% end %>
            <%= content_tag :li, class: ('active' if (controller_name == 'account' && action_name.eql?('index'))) do %>
              <a href="<%= accounts_path %>">Sales</a>
            <% end %>
            <%= content_tag :li, class: ('active' if controller_name == 'credit_debit') do %>
              <a href="<%= credit_debit_index_path %>">Accounts</a>
            <% end %>
            <%= content_tag :li, class: ('active' if controller_name == 'locations') do %>
              <a href="#">Location</a>
            <% end %>
            <%= content_tag :li, class: ('active' if controller_name == 'contacts') do %>
              <a href="#">Contact</a>
            <% end %>
            <% if user_signed_in? %>
              <% manage_url = current_user.is_admin? ? accounts_manage_path : edit_user_registration_path %>
              <%= content_tag :li, class: ('active' if (controller_name == 'account' && action_name.eql?('manage'))) do %>
                <a href="<%= manage_url %>"><%= current_user.email %></a>
              <% end %>
              <%= content_tag :li do %>
                <a href="<%= destroy_user_session_path %>">Log Out</a>
              <% end %>
            <% end %>
          </ul>
      </div>
      <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/login.html.erb
<form class="form-signin">
	<h2 class="form-signin-heading">Sign In</h2>
	<input type="text" class="form-control" placeholder="Email address" required="" autofocus="">
	<input type="password" class="form-control" placeholder="Password" required="">
	<label class="checkbox">
	  <input type="checkbox" value="remember-me"> Remember me
	</label>
	<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>